### ISSUE TITLE
Le 3 passwords (admin123 e user123) non fungono

### ISSUE THREAD

**Issue by palladius** [gdgpescara/app-mod-workshop#2]
Non so se sia a causa di un mistmatch di PHP VERSION, ma da me le 3 password non vanno.
https://github.com/gdgpescara/app-mod-workshop/blob/35e71a981a53299319da1ff209be2b4e7b3e20c6/db/02_seed.sql#L5

Ho provato a copiare l'hash in un nuovo utente (riccardo) e continua a non andare.
Ho letto la documentazione delkla funzione e copiato l'hash da li, e funge.

```sql

-- this still doesnt work
INSERT INTO users (username, password, role) VALUES
('riccardo', '$2y$10$yfU8F5v/OAVYoZz2EB6gNOozF.SAqA.VduOASCN5UuMJPmq41E7be', 'user');   -- Password: user123

-- This hash (taken from https://www.php.net/manual/en/function.password-verify.php) DOES work
INSERT INTO users (username, password, role) VALUES
('rasmuslerdorf','$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a', 'admin');   -- Password: rasmuslerdorf
```

**Comment by gregoriopalama** [comment]
Changed passwords after regenerating them with bcrypt
